productName: wbcs
appId: wbcs

directories:
  output: dist/electron

copyright: Copyright © 2020 wbcs

dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications

    - x: 130
      'y': 150
      type: file
